# Generated by Django 5.1.5 on 2025-01-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=12)),
                ('github_user', models.CharField(default='Username', max_length=58)),
                ('mentor_dept', models.CharField(choices=[('CSE', 'CSE'), ('CAI', 'CAI'), ('CSD', 'CSD'), ('CSM', 'CSM'), ('CSC', 'CSC'), ('CST', 'CST'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('CE', 'CE'), ('ME', 'ME')], default='CSE', max_length=20)),
                ('year', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=12)),
                ('leetcode_user', models.CharField(default='Username', max_length=58)),
                ('dept', models.CharField(choices=[('CSE', 'CSE'), ('CAI', 'CAI'), ('CSD', 'CSD'), ('CSM', 'CSM'), ('CSC', 'CSC'), ('CST', 'CST'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('CE', 'CE'), ('ME', 'ME')], default='CSE', max_length=20)),
                ('year', models.IntegerField(default=3)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('web_mem', models.CharField(max_length=20)),
                ('rank', models.IntegerField(default=1)),
                ('rating', models.FloatField(default=0.0)),
                ('project_score', models.FloatField(default=0.0)),
            ],
        ),
    ]
