# Generated by Django 5.1.5 on 2025-01-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_student_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='mentor_id',
            field=models.CharField(default='Mentor ID', max_length=20),
        ),
    ]
